import { STAT_KEYS } from './editorParameters.js';
import { getWeaponParameterDefinition } from './weaponParameters.js';


const PARAMETER_RELATIONSHIPS = [
  { section: 'structure', title: 'Construction economy', description: 'Cost and build work combine to determine how expensive and slow a unit is to field.', keys: ['metalcost', 'energycost', 'buildtime', 'workertime'] },
  { section: 'structure', title: 'Durability and physics', description: 'Health, mass, and regeneration shape survivability and impulse response.', keys: ['health', 'mass', 'autoheal'] },
  { section: 'structure', title: 'Detection profile', description: 'Visual, radar, sonar, and stealth values determine when this unit can see or be seen.', keys: ['sightdistance', 'radardistance', 'sonardistance', 'stealth', 'sonarstealth'] },
  { section: 'structure', title: 'Resource production', description: 'Production, extraction, and storage should be balanced as one economy package.', keys: ['metalmake', 'extractsmetal', 'energymake', 'metalstorage', 'energystorage'] },
  { section: 'structure', title: 'Cloak economy', description: 'Cloak drain is safest to tune alongside energy income and storage.', keys: ['cloakcost', 'cloakcostmoving', 'energymake', 'energystorage'] },
  { section: 'structure', title: 'Converter output', description: 'Conversion capacity and efficiency jointly control the converter’s useful output.', keys: ['customparams.energyconv_capacity', 'customparams.energyconv_efficiency', 'energymake'] },
  { section: 'structure', title: 'Engagement behaviour', description: 'Attack permission, automatic fire, manual fire, default states, and chase exclusions form the unit engagement policy.', keys: ['canattack', 'noautofire', 'canmanualfire', 'firestate', 'movestate', 'nochasecategory'] },
  { section: 'mobility', title: 'Movement response', description: 'Top speed, acceleration, braking, and turning determine the complete handling profile.', keys: ['maxvelocity', 'acceleration', 'brakerate', 'turnrate'] },
  { section: 'mobility', title: 'Terrain access', description: 'Slope and water-depth limits decide which parts of a map the unit can traverse.', keys: ['maxslope', 'maxwaterdepth', 'minwaterdepth'] },
  { section: 'mobility', title: 'Transport behavior', description: 'Capacity, transport eligibility, and mass interact with carrying roles.', keys: ['transportcapacity', 'cantbetransported'] },
  { section: 'mobility', title: 'Aircraft altitude', description: 'Cruise altitude should be tuned together with aircraft speed and maneuvering.', keys: ['cruisealt', 'maxvelocity', 'turnradius', 'maxbank', 'maxpitch'] },
  { section: 'weapons', title: 'Damage throughput', description: 'Damage, reload, projectile count, and burst timing combine into sustained DPS.', keys: ['damage', 'reload', 'projectiles', 'burst', 'burstrate'] },
  { section: 'weapons', title: 'Armor damage profile', description: 'BAR armor-class values override base damage for matching targets.', keys: ['damage', 'damage_vs_vtol', 'damage_vs_subs', 'damage_vs_commander', 'damage_vs_shields', 'damage_vs_scavboss', 'damage_vs_raptorqueen', 'damage_vs_raptor', 'damage_vs_mines'] },
  { section: 'weapons', title: 'Range and projectile travel', description: 'Range must be reachable within projectile speed, acceleration, and lifetime limits.', keys: ['range', 'velocity', 'flighttime', 'startvelocity', 'weaponacceleration', 'burnblow'] },
  { section: 'weapons', title: 'Accuracy and leading', description: 'Spread, movement error, prediction, and firing tolerance jointly determine practical hit rate.', keys: ['accuracy', 'sprayangle', 'movingaccuracy', 'targetmoveerror', 'predictboost', 'leadlimit', 'leadbonus', 'tolerance', 'firetolerance'] },
  { section: 'weapons', title: 'Splash behavior', description: 'Area, edge damage, impact rules, and self-damage define how explosions apply damage.', keys: ['aoe', 'edgeeffectiveness', 'impactonly', 'noexplode', 'noselfdamage'] },
  { section: 'weapons', title: 'Guidance and trajectory', description: 'Tracking, turn rate, arc, and flight motion determine whether guided shots can connect.', keys: ['tracks', 'turnrate', 'trajectoryheight', 'wobble', 'dance', 'flighttime'] },
  { section: 'weapons', title: 'Collision and bounce', description: 'Collision masks and bounce retention control how a projectile interacts with the world.', keys: ['collidefriendly', 'collidefeature', 'collideneutral', 'collideground', 'collisionSize', 'groundbounce', 'waterbounce', 'numbounce', 'bounceslip', 'bouncerebound'] },
  { section: 'weapons', title: 'Unit engagement behaviour', description: 'Attack permission, automatic fire, manual fire, default states, and chase exclusions determine how the active weapon is used.', keys: ['canattack', 'noautofire', 'canmanualfire', 'firestate', 'movestate', 'nochasecategory', 'commandfire'] },
  { section: 'weapons', title: 'Target eligibility', description: 'Ground, air, water, and category masks jointly decide which targets are valid or preferred.', keys: ['canattackground', 'toairweapon', 'waterweapon', 'firesubmersed', 'onlytargetcategory', 'badtargetcategory'] },
  { section: 'weapons', title: 'Stockpile and shot cost', description: 'Ammunition timing, limits, and per-shot resources determine firing availability.', keys: ['stockpile', 'stockpiletime', 'stockpilelimit', 'energypershot', 'metalpershot'] },
  { section: 'weapons', title: 'Beam behavior', description: 'Beam duration, burst mode, sweep behavior, and falloff shape delivered damage.', keys: ['beamtime', 'beamburst', 'sweepfire', 'minintensity', 'duration', 'hardstop', 'falloffrate'] },
  { section: 'weapons', title: 'Projectile presentation', description: 'Trail, model, impact effect, colors, thickness, and intensity form one visual language.', keys: ['cegTag', 'model', 'explosiongenerator', 'rgbcolor', 'rgbcolor2', 'thickness', 'corethickness', 'laserflaresize', 'intensity'] },
  { section: 'weapons', title: 'Weapon audio', description: 'Fire, impact, and water-impact sounds should be authored as a coordinated set.', keys: ['soundstart', 'soundhit', 'soundhitwet'] },
  { section: 'weapons', title: 'Explosion spawner', description: 'Payload, surface, selection mode, lifetime, stun, CEG, and shield interaction are read together by BAR’s explosion-spawner gadget.', keys: ['spawns_name', 'spawns_surface', 'spawns_mode', 'spawns_expire', 'spawns_ceg', 'spawns_stun', 'spawn_blocked_by_shield'] },
  { section: 'weapons', title: 'Carrier deployment', description: 'Carrier payload, timing, capacity, costs, control range, direct control, and death behavior form one gadget-backed system.', keys: ['carried_unit', 'dronetype', 'spawnrate', 'maxunits', 'startingdronecount', 'spawn_metal_cost', 'spawn_energy_cost', 'controlradius', 'engagementrange', 'manualdrones', 'carrierdeaththroe'] },
  { section: 'weapons', title: 'Carrier docking and endurance', description: 'Docking, healing, formation, decay, flight time, and ammunition determine the deployed squadron lifecycle.', keys: ['enabledocking', 'dockingpieces', 'dockingradius', 'dockinghelperspeed', 'dockingarmor', 'dockinghealrate', 'docktohealthreshold', 'attackformationspread', 'attackformationoffset', 'decayrate', 'deathdecayrate', 'holdfireradius', 'droneminimumidleradius', 'droneairtime', 'dronedocktime', 'droneammo'] },
  { section: 'weapons', title: 'Cluster behavior', description: 'Cluster submunitions depend on a valid supporting WeaponDef and a practical projectile count.', keys: ['cluster_def', 'cluster_number'] },
  { section: 'weapons', title: 'Special projectile behavior', description: 'BAR’s custom-weapon gadget can reshape projectile flight, targeting, splitting, or water entry. Select one verified behavior and tune only the fields that belong to it.', keys: ['speceffect', 'spread_angle', 'max_range_reduction', 'cruise_min_height', 'cruise_max_height', 'lockon_dist', 'guidance_lost_radius', 'speceffect_def', 'speceffect_number', 'splitexplosionceg', 'waterpenceg', 'speceffect_cegtag', 'speceffect_model', 'tracking_turn_radius', 'accuracy', 'sprayangle'] },
  { section: 'weapons', title: 'Projectile interception', description: 'Targetable and interceptor bitmasks must share a channel; coverage controls the acquisition radius and exclusive interception prevents duplicate commitments.', keys: ['targetable', 'interceptor', 'coverage', 'interceptsolo', 'commandfire'] }
];

const PARAMETER_LABEL_OVERRIDES = {
  aoe: 'Splash AoE', cegTag: 'Visual Effect / Trail', collisionSize: 'Collision Size',
  canattackground: 'Can Target Ground', toairweapon: 'Anti-Air Only',
  onlytargetcategory: 'Allow Targets', badtargetcategory: 'De-prioritise Targets',
  soundstart: 'Fire Sound', soundhit: 'Hit Sound', soundhitwet: 'Water Hit Sound'
};

const BASE_PARAMETER_HELP = {
  metalcost: 'Metal required to build the unit.', energycost: 'Energy required to build the unit.', buildtime: 'Base work required to finish construction.', health: 'Maximum hit points before destruction.',
  maxvelocity: 'Maximum movement speed.', acceleration: 'How quickly the unit reaches speed.', brakerate: 'How quickly the unit slows down.', mass: 'Affects collision and impulse reactions.',
  sightdistance: 'Visual detection range.', radardistance: 'Radar detection range.', sonardistance: 'Underwater detection range.', stealth: 'Prevents radar detection.', sonarstealth: 'Prevents sonar detection.',
  workertime: 'Build, repair, reclaim, and terraform power.', metalmake: 'Passive metal production.', extractsmetal: 'Metal extraction amount.', energymake: 'Passive energy production.',
  metalstorage: 'Maximum stored metal.', energystorage: 'Maximum stored energy.', cloakcost: 'Energy used per second while cloaked.', cloakcostmoving: 'Energy used per second while moving while cloaked.',
  builddistance: 'Maximum building and repair range.', maxslope: 'Steepest terrain the unit can use.', maxwaterdepth: 'Deepest water the unit can enter.', minwaterdepth: 'Minimum water depth required.',
  transportcapacity: 'Number of transport slots provided.', cantbetransported: 'Prevents the unit from being carried.', cruisealt: 'Preferred aircraft altitude.',
  'customparams.techlevel': 'Technology tier used by BAR content and filters.', 'customparams.energyconv_capacity': 'Energy-converter capacity custom parameter.', 'customparams.energyconv_efficiency': 'Energy-converter efficiency custom parameter.',
  'customparams.carried_unit': 'Unit ID deployed by BAR carrier behavior.', 'customparams.spawnrate': 'Seconds between carrier deployment attempts.', 'customparams.maxunits': 'Maximum number of active carried units.',
  'customparams.controlradius': 'Experimental radius within which deployed units remain under carrier control.', 'customparams.manualdrones': 'Allows the player to select and issue orders to deployed units while their carrier is alive.', 'customparams.enabledocking': 'Experimental docking behavior for returning carried units.',
  'customparams.decayrate': 'Health decay applied to deployed units.', 'customparams.deathdecayrate': 'Decay applied after the carrier is destroyed.', 'customparams.carrierdeaththroe': 'Carrier death behavior, such as release.',
  'customparams.metalcost': 'Metal charged for each carrier-deployed unit.', 'customparams.energycost': 'Energy charged for each carrier-deployed unit.',
  footprintx: 'Unit footprint width in 16-elmo map squares. Yard-map rows should use this width.', footprintz: 'Unit footprint depth in 16-elmo map squares. Yard-map row count should match this depth.',
  yardmap: 'Building occupancy map. Separate rows with spaces; each row should match the footprint width.', maxthisunit: 'Maximum number of this UnitDef that one team may own at once.',
  objectname: '3D model path already present in BAR or the loaded mod.', script: 'Unit animation script path already present in BAR or the loaded mod.',
  buildpic: 'Build-menu artwork name already present in BAR or the loaded mod.', icontype: 'Strategic map icon type registered by BAR or the loaded mod. Choose a bundled tactical icon or enter a custom type.',
  collisionvolumetype: 'Collision shape such as Box, CylY, Ell, Footprint, or Sphere.', collisionvolumescales: 'Collision volume dimensions as three space-separated numbers.',
  collisionvolumeoffsets: 'Collision volume X Y Z offset as three space-separated numbers.',
  canattack: 'Allows the unit to receive and execute ordinary attack orders.', noautofire: 'Stops the unit from automatically firing while preserving explicit weapon control.',
  canmanualfire: 'Makes the unit eligible for the manual-fire command when a weapon supports it.', firestate: 'Initial fire posture: hold fire, return fire, or fire at will.',
  movestate: 'Initial pursuit posture: hold position, maneuver, or roam.', nochasecategory: 'Space-separated categories the unit should not automatically pursue.',
  damage: 'Base damage against targets without a specific armor class.', reload: 'Seconds between firing cycles.', range: 'Maximum firing range in elmos.', velocity: 'Projectile speed.',
  flighttime: 'How long a guided projectile retains fuel and guidance.', aoe: 'Explosion diameter that can damage nearby units.', accuracy: 'Base shot spread; lower is more accurate.',
  sprayangle: 'Spread between projectiles in a burst.', heightmod: 'How range changes with target elevation.', randomdecay: 'Legacy projectile spread behavior; use with caution.',
  hightrajectory: 'Cannon arc mode: low, high, or player-toggleable.', projectiles: 'Projectiles released per firing event.', burst: 'Shots fired in one burst.', burstrate: 'Delay between shots inside a burst.',
  canattackground: 'Allows force-firing at a ground position.', toairweapon: 'Legacy anti-air convenience flag. Prefer target categories for precise control.', stockpile: 'Requires ammunition to be stockpiled before firing.',
  avoidfriendly: 'Makes projectiles try to avoid friendly units.', collidefriendly: 'Allows projectile collision with friendly units.', interceptedbyshieldtype: 'Shield interception bitmask. Zero means shields do not intercept it.',
  stockpiletime: 'Seconds required to produce one stockpiled round.', stockpilelimit: 'Custom maximum number of stockpiled rounds.', weapontype: 'Engine projectile behavior class.',
  cegTag: 'Continuous effect emitted by the projectile while it travels.', model: '3D projectile model file.', explosiongenerator: 'Custom explosion effect spawned on impact.',
  edgeeffectiveness: 'Fraction of base damage retained at the outer edge of splash range.', impactonly: 'Deals damage only through direct impact, not splash.',
  noexplode: 'Projectile continues after impact. Can multiply damage while inside a collision volume.', burnblow: 'Explodes when it reaches maximum range.', noselfdamage: 'Prevents the firing unit from taking its own explosion damage.',
  impulsefactor: 'Multiplier for knockback impulse.', impulseboost: 'Flat knockback added before the multiplier.', energypershot: 'Energy consumed each time the weapon fires.', metalpershot: 'Metal consumed each time the weapon fires.',
  spawns_name: 'Space-separated UnitDef IDs created when this weapon explodes.', spawns_surface: 'Restricts explosion spawning to LAND or SEA.', spawns_mode: 'How a multi-unit spawn list is selected: random, locked random, or sequential.',
  spawns_expire: 'Seconds before an explosion-spawned unit is destroyed.', spawns_ceg: 'Additional CEG emitted when an explosion creates a unit.', spawns_stun: 'Seconds an explosion-spawned unit remains stunned.',
  spawn_blocked_by_shield: 'Allows a shield collision to prevent the explosion-spawned payload.', carried_unit: 'Space-separated UnitDef IDs managed by BAR’s carrier gadget.',
  dronetype: 'Optional carrier behavior type for each carried UnitDef.', spawnrate: 'Approximate seconds between carrier spawn attempts.', maxunits: 'Maximum active carried units; supports one value per carried UnitDef.',
  startingdronecount: 'Number of carried units created when the carrier finishes construction.', spawn_metal_cost: 'Metal charged for each carrier-deployed unit.', spawn_energy_cost: 'Energy charged for each carrier-deployed unit.',
  controlradius: 'Distance at which deployed units are recalled to the carrier; zero disables the limit.', engagementrange: 'Distance within which deployed units adopt the carrier’s active combat commands.', manualdrones: 'Keeps deployed units selectable for direct player commands inside BAR’s carrier system.',
  carrierdeaththroe: 'Drone behavior when the carrier dies: death, control, capture, release, or parasite.', enabledocking: 'Enables carrier docking and recall behavior.',
  dockingpieces: 'Model piece groups used as docking points. Separate pieces with spaces and groups with commas.', dockingradius: 'Distance at which a returning unit snaps or is helped onto a docking piece.',
  dockinghelperspeed: 'Movement speed used to guide a returning unit onto its docking piece.', dockingarmor: 'Damage multiplier while docked; 0.2 means 20% damage taken.',
  dockinghealrate: 'Hit points restored per second while docked.', docktohealthreshold: 'Health percentage below which a deployed unit returns for repair.',
  attackformationspread: 'Spacing between docked units when they launch into an attack formation.', attackformationoffset: 'Percentage of target distance used before drones begin their direct approach.',
  decayrate: 'Health lost per second while a carried unit is undocked.', deathdecayrate: 'Health lost per second after a carried unit loses its carrier.',
  holdfireradius: 'Wander radius used while the carrier is set to hold fire.', droneminimumidleradius: 'Minimum idle radius used when docking is unavailable.',
  droneairtime: 'Maximum seconds a deployed unit stays undocked before returning.', dronedocktime: 'Minimum seconds a unit remains docked.', droneammo: 'Ammunition assigned to each deployed unit.',
  cluster_def: 'WeaponDef key released as cluster submunitions.', cluster_number: 'Number of submunitions released by the cluster projectile.',
  speceffect: 'Select one behavior implemented by BAR’s custom-weapon gadget. Inherited keeps the original WeaponDef behavior.',
  spread_angle: 'Total left-to-right sector width in degrees. BAR’s Tremor uses 22°. This is randomized inside the sector, not evenly spaced.',
  max_range_reduction: 'Maximum fraction removed from horizontal projectile speed to vary shot depth. BAR requires a value from 0 to 1 and Tremor uses 0.30.',
  cruise_min_height: 'Minimum terrain clearance maintained during cruise flight.',
  cruise_max_height: 'Maximum terrain clearance maintained during cruise flight. Keep this at or above the minimum.',
  lockon_dist: 'Distance from the target where terrain-following cruise movement gives way to the final approach.',
  guidance_lost_radius: 'Random scatter radius used when primary-weapon guidance loses a valid target.',
  speceffect_def: 'WeaponDef spawned after a split or water-penetration transition. It must exist on this unit or in an enabled supporting definition.',
  speceffect_number: 'Number of child projectiles created by the split behavior.',
  splitexplosionceg: 'Optional CEG emitted where the parent projectile divides into its children.',
  waterpenceg: 'Optional CEG emitted when a cannon projectile transitions at the water surface.',
  speceffect_cegtag: 'Trail CEG assigned to the child projectile. This is separate from the parent WeaponDef trail.',
  speceffect_model: 'Model assigned to the child projectile. This is separate from the parent WeaponDef model.',
  tracking_turn_radius: 'Horizontal turn radius used while torpedo water correction steers toward its target.',
  paralyzer: 'Turns damage into paralysis rather than hit-point loss.', paralyzetime: 'Maximum paralysis duration.', mygravity: 'Overrides map gravity for ballistic weapons.', heightboostfactor: 'Terrain-height effect on cannon range.',
  startvelocity: 'Projectile speed immediately after launch.', weaponacceleration: 'Speed gained per second until maximum velocity.', tracks: 'Enables homing guidance.', turnrate: 'How quickly a guided projectile can turn.',
  trajectoryheight: 'Guided missile arc height.', wobble: 'Random direction variation during flight.', dance: 'Random positional variation during flight.', fixedlauncher: 'Uses the firing piece orientation at launch.',
  smoketrail: 'Emits the weapon type’s smoke trail.', waterweapon: 'Can target underwater units and pass through water.', firesubmersed: 'Allows the weapon to fire while underwater.',
  movingaccuracy: 'Shot spread while the firing unit is moving.', targetmoveerror: 'Random error based on target movement.', predictboost: 'How strongly the weapon predicts target movement.',
  leadlimit: 'Maximum distance used when leading a target; -1 is unlimited.', leadbonus: 'Experience bonus added to lead limit.', targetborder: 'Aim point from far edge to near edge of the target.',
  cylindertargeting: 'Uses cylindrical instead of spherical range behavior.', tolerance: 'Aim error allowed before the weapon may fire.', firetolerance: 'Final angle check that stops sideways shots.',
  proximitypriority: 'Target-priority multiplier based on distance.', collidefeature: 'Whether projectiles collide with map features.', collideneutral: 'Whether projectiles collide with neutral units.',
  collideground: 'Whether projectiles collide with terrain.', collisionSize: 'Projectile collision size; engine effect varies by weapon type.', groundbounce: 'Enables bouncing off terrain.',
  waterbounce: 'Enables bouncing off water.', numbounce: 'Number of bounces before explosion; -1 permits unlimited bounces.', bounceslip: 'Horizontal velocity kept after a bounce.',
  bouncerebound: 'Vertical velocity kept after a bounce.', beamtime: 'Beam duration; damage is distributed across this time.', beamburst: 'Uses burst behavior instead of continuous beam timing.',
  sweepfire: 'Allows a beam to continue while aiming at a new target.', minintensity: 'Minimum beam damage retained at maximum range.', duration: 'Visual laser length multiplier.',
  hardstop: 'Stops a laser projectile sharply instead of fading out.', falloffrate: 'Laser fade rate after maximum range.', thickness: 'Beam or laser width.',
  corethickness: 'Width of the beam’s bright core.', laserflaresize: 'Size of the firing flare.', intensity: 'Visual transparency/intensity for sprite projectiles.',
  rgbcolor: 'Primary projectile RGB color, for example “1 0.2 0.2”.', rgbcolor2: 'Secondary/core projectile RGB color.', explosionscar: 'Leaves an explosion scar on terrain.',
  alwaysvisible: 'Renders the projectile even outside line of sight.', soundstart: 'Sound asset played when firing.', soundhit: 'Sound asset played on impact.', soundhitwet: 'Sound asset played on water impact.',
  onlytargetcategory: 'Categories this slot is allowed to target.', badtargetcategory: 'Categories this slot de-prioritizes but can still target.',
  explodeas: 'WeaponDef used when the unit is destroyed normally.', selfdestructas: 'WeaponDef used when the unit completes a self-destruct.', selfdestructcountdown: 'Seconds between issuing self-destruct and detonation.',
  death_explosion_damage: 'Default damage for an isolated copy of this unit’s normal death explosion.', death_explosion_aoe: 'Damage diameter for this unit’s isolated normal death explosion.',
  death_explosion_camerashake: 'Camera-shake strength generated by normal destruction.', death_explosion_impulsefactor: 'Knockback multiplier generated by normal destruction.',
  selfd_explosion_damage: 'Default damage for an isolated copy of this unit’s self-destruct explosion.', selfd_explosion_aoe: 'Damage diameter for this unit’s isolated self-destruct explosion.',
  selfd_explosion_camerashake: 'Camera-shake strength generated by self-destruction.', selfd_explosion_impulsefactor: 'Knockback multiplier generated by self-destruction.',
  damagemodifier: 'Multiplier applied to incoming damage; lower values make the unit tougher.', energyupkeep: 'Energy consumed continuously while the unit is active.', metalupkeep: 'Metal consumed continuously while the unit is active.',
  avoidfeature: 'Makes aiming avoid terrain features when checking a safe firing line.', cratermult: 'Multiplier controlling terrain deformation strength.', crateraoe: 'Diameter of terrain deformation, separate from damage AoE.',
  targetable: 'Bitmask describing which interceptor channels can target this projectile.', interceptor: 'Bitmask describing which targetable projectile channels this weapon intercepts.', coverage: 'Radius in which an interceptor searches for projectiles.',
  interceptsolo: 'When enabled, other interceptors will not target a projectile after this interceptor commits to it.', commandfire: 'Makes the weapon respond to manual-fire orders instead of automatic attack.',
  gravity: 'Global map gravity override.', windmin: 'Minimum map wind strength.', windmax: 'Maximum map wind strength.', tidalmaker: 'Global tidal energy yield.'
};

// Keep field documentation explicit. These fields are all exposed in the editor,
// so a generic "enter a value" fallback is not useful enough for safe tuning.
const ADDITIONAL_PARAMETER_HELP = Object.freeze({
  // Unit resilience, sensing, economy, and cloaking.
  autoheal: 'Hit points restored per second while the unit is active. This is separate from idle regeneration.',
  canselfdestruct: 'Enables the self-destruct command. Disabling it prevents the player from starting a self-destruct countdown.',
  crushresistance: 'Mass threshold used when resolving crush interactions. Raise it to make the unit harder for heavier movers to crush.',
  blocking: 'Makes the unit block movement and pathfinding. Disable only for units intended to be passed through.',
  collide: 'Allows normal physical collision response. It does not by itself decide whether the unit blocks pathfinding.',
  pushresistant: 'Reduces displacement from physical pushing and collision impulses.',
  upright: 'Keeps the model upright instead of tilting to match terrain. Useful for buildings and rigid props.',
  waterline: 'Vertical model offset used at the water surface. Adjust with care because it changes how a floating model sits in water.',
  seismicsignature: 'Strength of the unit seismic signature. A negative or zero value usually removes meaningful seismic detection.',
  idleautoheal: 'Hit points restored per second after the unit has been idle for the configured idle time.',
  idletime: 'Seconds the unit must remain idle before idle regeneration begins.',
  windgenerator: 'Energy output coefficient driven by map wind. Actual production depends on the lobby map wind range.',
  tidalgenerator: 'Tidal energy output coefficient. Actual production depends on the map tidal strength.',
  cancloak: 'Allows cloaking when the unit has a valid cloak economy. Check cloak cost and decloak rules together.',
  initcloaked: 'Starts the unit cloaked when cloaking is available.',
  mincloakdistance: 'Distance at which nearby enemies force decloaking. Zero leaves no proximity safety buffer.',
  decloakonfire: 'Reveals the unit when it fires a weapon.',
  decloakspherical: 'Uses a spherical proximity check for cloak disruption instead of a flatter horizontal check.',
  airsightdistance: 'Visual detection range used specifically for airborne targets. It can differ from ordinary sight distance.',
  radardistancejam: 'Radius in which the unit jams enemy radar detection.',
  sonardistancejam: 'Radius in which the unit jams enemy sonar detection.',
  seismicdistance: 'Radius at which the unit can detect seismic signatures.',
  repairspeed: 'Build-work per second available for repairing. It normally follows worker power unless explicitly overridden.',
  reclaimspeed: 'Build-work per second available for reclaiming features and units.',
  resurrectspeed: 'Build-work per second available for resurrecting wrecks when resurrection is supported.',
  capturespeed: 'Build-work per second available for capture actions when capture is supported.',
  terraformspeed: 'Build-work per second available for terrain terraforming.',
  canrepair: 'Enables repair orders and repair behavior for this unit.',
  canreclaim: 'Enables reclaim orders for features and units.',
  canresurrect: 'Enables resurrection orders where the loaded game supports resurrection.',
  cancapture: 'Enables capture orders where the loaded game supports capture.',
  canassist: 'Allows the unit to assist allied construction, repair, and related builder work.',
  canbeassisted: 'Allows other builders to assist this unit while it is constructing or working.',
  maxreversevelocity: 'Maximum reverse movement speed. Zero prevents meaningful reverse travel.',
  turninplace: 'Allows the unit to rotate without moving forward.',
  turninplaceanglelimit: 'Angle threshold before the unit chooses to turn in place rather than continue moving.',
  turninplacespeedlimit: 'Speed threshold used by the engine for turn-in-place handling. Tune with turn rate and acceleration.',
  separationdistance: 'Preferred spacing from nearby units in movement and formation handling.',
  maxbank: 'Maximum aircraft roll while turning. Higher values create more aggressive banking.',
  maxpitch: 'Maximum aircraft pitch while climbing or diving.',
  turnradius: 'Minimum practical aircraft turn radius. Lower values produce tighter turns.',
  maxaileron: 'Aircraft roll-control authority. Increase carefully because it changes turning response.',
  maxelevator: 'Aircraft pitch-control authority for climbing and diving response.',
  maxrudder: 'Aircraft yaw-control authority used during turning and alignment.',
  hoverattack: 'Lets aircraft attack while hovering or holding position when their movement definition supports it.',
  airstrafe: 'Lets aircraft use strafing movement during attack runs instead of always turning directly toward the target.',
  transportsize: 'Total transport size capacity available to carried units.',
  transportmass: 'Total mass capacity available to carried units.',
  mintransportsize: 'Minimum transport-size value a passenger must meet or exceed to be accepted.',
  mintransportmass: 'Minimum passenger mass value required for transport eligibility.',
  loadingradius: 'Distance within which a transport can load an eligible passenger.',
  unloadspread: 'Spacing applied when passengers are unloaded. Higher values reduce stacking at the drop point.',
  transportunloadmethod: 'Engine unload behavior mode. Verify the selected method in-game because transport movement definitions affect it.',
  releaseheld: 'Releases a carried unit when the transport is destroyed or forced to drop its payload.',
  holdsteady: 'Keeps transported units steady relative to the carrier instead of allowing normal positional drift.',
  transportbyenemy: 'Allows enemy transports to load this unit when their transport rules otherwise permit it.',
  kamikaze: 'Turns the unit into a self-sacrificing attacker when it reaches its configured attack distance.',
  kamikazedistance: 'Distance from the target at which a kamikaze unit triggers its self-destructive attack.',

  // Weapon impact, collision, visuals, mounts, dynamic damage, and shields.
  explosionspeed: 'Rate at which the impact explosion expands. It mainly affects explosion timing and presentation.',
  camerashake: 'Camera-shake strength caused by the impact. It changes presentation, not damage.',
  craterboost: 'Additional terrain-deformation contribution added to the crater strength.',
  scarttl: 'Lifetime of the terrain scar or decal left by the explosion.',
  firestarter: 'Chance or strength used by fire-starting weapon behavior. Runtime results depend on the loaded fire system.',
  weaponTimer: 'Time used by weapon classes with a vertical launch or delayed flight phase. Only relevant to supporting weapon behavior.',
  windup: 'Delay before a volley begins after the weapon receives a valid firing opportunity.',
  gravityaffected: 'Lets map gravity alter the projectile flight path. Most useful for ballistic projectiles.',
  submissile: 'Allows a torpedo-style missile to leave water when its weapon behavior supports that transition.',
  avoidground: 'Makes the projectile attempt to avoid terrain when its weapon class supports avoidance checks.',
  avoidneutral: 'Makes the projectile attempt to avoid neutral units during its avoidance checks.',
  collideenemy: 'Allows collision with enemy units that are not necessarily the current target.',
  collidenontarget: 'Allows collision with units other than the weapon current target.',
  collidecloaked: 'Allows collision with cloaked units when other engine detection rules permit the interaction.',
  beamttl: 'Number of frames a beam visual remains after emission. It affects appearance rather than the firing cycle.',
  beamdecay: 'Rate at which a beam visual fades after emission.',
  largebeamlaser: 'Enables the large-beam visual treatment for beam-laser weapon classes.',
  soundhitdry: 'Sound asset played when a projectile impacts dry ground or a dry target surface.',
  soundstartvolume: 'Playback volume multiplier for the firing sound.',
  soundhitvolume: 'Playback volume multiplier for the general impact sound.',
  soundhitwetvolume: 'Playback volume multiplier for the water-impact sound.',
  soundhitdryvolume: 'Playback volume multiplier for the dry-impact sound.',
  texture1: 'Primary texture used by the projectile or beam visual. The named asset must exist in the loaded game or mod.',
  texture2: 'Secondary texture layer used by the projectile or beam visual.',
  texture3: 'Tertiary texture layer used by the projectile or beam visual.',
  colormap: 'Color and alpha sequence used by compatible projectile effects. Keep the format expected by the weapon class.',
  smokecolor: 'Color value used by compatible smoke-trail rendering.',
  smokeperiod: 'Frames or time between smoke emissions for compatible weapon classes.',
  smokesize: 'Initial size of emitted smoke particles.',
  smoketime: 'Lifetime of emitted smoke particles.',
  castshadow: 'Lets the projectile cast a world shadow when the weapon visual supports it.',
  smoketrailcastshadow: 'Lets the smoke trail cast a world shadow when the trail visual supports it.',
  size: 'Base projectile visual size for compatible weapon classes.',
  sizedecay: 'Amount a projectile visual shrinks over its lifetime.',
  sizegrowth: 'Amount a projectile visual grows over its lifetime.',
  alphadecay: 'Rate at which projectile visual opacity fades over time.',
  stages: 'Number of visual stages used by a compatible staged projectile effect.',
  tilelength: 'Length of one repeated beam-texture tile.',
  scrollspeed: 'Speed at which a beam or projectile texture scrolls.',
  turret: 'Allows this weapon mount to rotate independently toward its target.',
  slaveto: 'Weapon slot this mount follows for aim direction. Use a valid existing slot number.',
  maindir: 'Preferred local aim direction as a three-number vector. It constrains fixed or limited-arc mounts.',
  maxangledif: 'Maximum angle away from the preferred mount direction that the weapon may aim.',
  weaponaimadjustpriority: 'Ordering priority used when the engine resolves competing weapon aim adjustments.',
  fastautoretargeting: 'Uses faster automatic retargeting updates. It can improve responsiveness at additional simulation cost.',
  fastquerypointupdate: 'Updates the weapon query point more often for faster aiming response.',
  burstcontrolwhenoutofarc: 'Controls how a burst behaves when the target leaves the permitted firing arc.',
  accurateleading: 'Number of extra lead-calculation iterations. Higher values may improve accuracy at additional computation cost.',
  dyndamageinverted: 'Inverts the direction of the dynamic damage curve over distance.',
  dyndamageexp: 'Exponent shaping the dynamic damage curve over distance.',
  dyndamagemin: 'Lowest damage value permitted by the dynamic damage curve.',
  dyndamagerange: 'Distance over which the dynamic damage curve is evaluated.',
  shieldrepulser: 'Makes a compatible shield push projectiles away instead of only absorbing them.',
  shieldsmart: 'Lets a compatible shield avoid blocking allied projectiles when its runtime behavior supports pass-through.',
  shieldexterior: 'Places a compatible shield outside the unit collision volume instead of using an interior shield model.',
  shieldvisible: 'Shows the shield visual when the loaded game shield renderer supports it.',
  shieldmaxspeed: 'Maximum projectile speed a repulsor shield can meaningfully affect.',
  shieldforce: 'Force applied by a repulsor shield to affected projectiles.',
  shieldradius: 'Radius of the shield interception or repulsion volume.',
  shieldpower: 'Maximum shield energy or capacity.',
  shieldstartingpower: 'Shield capacity available immediately after the unit is created.',
  shieldpowerregen: 'Shield capacity restored per second.',
  shieldpowerregenenergy: 'Energy consumed for each unit of shield capacity regenerated.',
  shieldenergyuse: 'Shield energy consumed when it intercepts or affects a projectile.',
  shieldrechargedelay: 'Delay before shield regeneration resumes after an interception.',
  shieldintercepttype: 'Bitmask of projectile interceptor channels this shield can affect. It must match the projectile targetable mask.',
  dronetype: 'Drone navigation mode per carried unit type (e.g., sub, sea, air, land, default). Set to sub for submarine/underwater spawning from submerged structures.',
  spawns_surface: 'Allowed surface environment for unit spawning (LAND, SEA, WATER, SUB, BOTH). Set to SUB or WATER for underwater/naval spawning.',
});

const PARAMETER_HELP = Object.freeze({ ...BASE_PARAMETER_HELP, ...ADDITIONAL_PARAMETER_HELP });

export const PARAMETER_SECTION_GUIDANCE = {
  structure: 'Unit attributes apply to the selected unit. A changed field becomes a project override; Reset removes only that override.',
  mobility: 'Movement changes affect how the selected unit travels. Use small changes first, then validate in-game.',
  weapons: 'Values apply to the selected weapon slot. Inherited means the untouched BAR definition is used. Advanced fields are engine-specific; hover ? for behavior and constraints.'
};

export function getRelationshipLabel(key) {
  return STAT_KEYS.find(item => item.key === key)?.label
    || getWeaponParameterDefinition(key)?.label
    || PARAMETER_LABEL_OVERRIDES[key]
    || key.replace(/^customparams\./, '').replaceAll('_', ' ').replace(/\b\w/g, character => character.toUpperCase());
}

export function getParameterRelationship(section, key) {
  if (!key) return null;
  const matches = PARAMETER_RELATIONSHIPS.filter(group => group.section === section && group.keys.includes(key));
  if (matches.length === 0) return null;
  if (matches.length === 1) return matches[0];
  return {
    section,
    title: `${getRelationshipLabel(key)} connects ${matches.length} systems`,
    description: matches.map(group => group.title).join(' · '),
    keys: [...new Set(matches.flatMap(group => group.keys))]
  };
}

export function getParameterHelp(key, label) {
  if (key === 'turnrate' && label === 'Turn Rate') return 'How quickly the unit rotates.';
  if (PARAMETER_HELP[key]) return PARAMETER_HELP[key];
  if (key.startsWith('damage_vs_')) return `Damage against the ${key.replace('damage_vs_', '')} armor class.`;
  return `${label}. Enter a value to create an override; clear or reset it to return to the inherited game value.`;
}
